# Generated by Django 5.2.7 on 2025-10-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0003_remove_book_created_by_book_added_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
